// generated by eval/build-drops.mjs, do not edit
//
// How often each consonant is deleted, as [word-initial, medial, final].
// null where there was too little to count.
export const DROP: Record<string, Array<number | null>> = {
  j: [0.013, 0.077, null],
  k: [0.027, 0.109, 0.792],
  l: [0.013, 0.18, 0.6],
  m: [0.005, 0.053, 0.083],
  n: [0.005, 0.029, 0.012],
  p: [0.018, 0.053, 0.552],
  s: [0.027, 0.153, 0.778],
  t: [0.054, 0.133, 0.863],
  w: [0.032, 0.389, 0.826],
};
